---
- name: detach public ip from the nic
  hosts: localhost
  tasks:
        - name: detach public ip from the nic
          azure_rm_networkinterface:
              resource_group: "{{ azure_resource_group }}"
              name: "{{ azure_nic }}"
              virtual_network: "{{ azure_vnet }}"
              subnet: "{{ azure_subnet }}"
              security_group: "{{ azure_nsg }}"
              ip_configurations:
                - name: "{{ ip_config_name }}"
                  private_ip_address: "{{ azure_private_ip }}"
                  private_ip_allocation_method: Static
                  primary: yes

- name: delete iscsi pip
  hosts: localhost
  roles:
      - {role:  delete-azure-publicip, azure_resource_group: "{{ azure_resource_group }}", azure_public_ip: "{{ azure_public_ip }}"}
