---
# replace with download URL for SAPCAR
url_sapcar: 

# replace with download URL for HDB server
url_hdbserver: 

sap_sid: 
sap_instancenum: 
sap_hostname: "{{ ansible_hostname.lower() }}"

pwd_os_sapadm: 
pwd_os_sidadm: 
pwd_db_system: 
use_hana2:
hana1_db_mode:
